muscleInfo = [
    {
        //nameOfWorkout: string
//muscle group: string
//reps: number
//set: number
//description: string
//comments: array containing strings

        nameOfWorkout: "incline dumbell press",
        muscleGroup: "Chest",
        set: "3",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "bench press",
        muscleGroup: "Chest",
        set: "3",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "dumbells bench press",
        muscleGroup: "Chest",
        set: "3",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "dips",
        muscleGroup: "Chest",
        set: "3",
        reps: "8-12",
        comments:[""],
        nameOfWorkout: "banded push-ups",
        muscleGroup: "Chest",
        set: "3",
        reps: "6-12 or to failure",
        comments:[""],
        nameOfWorkout: "cable crossover",
        muscleGroup: "Chest",
        set:"3",
        reps: "10 +",        
        description: `" When it comes to the “best chest workout”, it really comes down to choosing exercises that allow symmetrical growth in the upper chest, middle chest, and lower chest while still providing overall mass to your chest. If your chest workout is unbalanced and favours one portion of your chest over the other, overtime this will lead to imbalances and take away from the aesthetics of your chest. In this video I’ll show you guys the best workout for chest based on scientific literature and our anatomical understanding of the body. It includes the best upper chest exercises, middle chest exercises, and lower chest exercises to help evenly shape and build your chest. 

        The upper chest will be prioritized through movements that involve shoulder flexion. The middle chest will be prioritized through any horizontal adducting movements that don’t involve shoulder flexion or extension. The lower chest will be prioritized through movements that involve shoulder extension. Although the chest exercises in this video have been carefully chosen through my analysis of many studies, it doesn’t account for every individual. So feel free to swap out some exercises for other chest exercises that you feel better chest activation with."`, 
        
        
    },{
        nameOfWorkout: "deadlifts",
        muscleGroup: "Back",
        set: "3",
        reps: "6-8",
        comments:[""],
        muscle: 'Back',
        nameOfWorkout: "Pull-Ups",
        muscleGroup: "Back",
        set: "4",
        reps: "6-12",
        comments:[""],
        nameOfWorkout: "chest-supported row",
        muscleGroup: "Back",
        set: "4",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "lat pulldowns",
        muscleGroup: "Back",
        set: "4",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "Scapular pull-ups",
        muscleGroup: "Back",
        set: "3",
        reps: "8 +",
        comments:[""],
        description: `"In this video I discuss the best back training workout that utilizes exercises for a big back, as well as exercises for a wider back based on current scientific literature and our anatomical understanding of the back muscles. It’s important that you not only choose the right exercises when performing a back workout for mass, but to also perform these exercises in the correct fashion to target the right muscles. If you’re looking to add more mass, depth, and width to your upper back and lower back while targeting muscles that are important for scapular and shoulder stability, then this is the best back workout video for you. 

        Within the video I’m going to discuss 5 exercises that I believe are essential to grow a powerful and attractive looking back: the deadlift, pull-up, chest-supported row, lat pulldown, and scapular pull-up. 
        
        I will go through each of these exercises and show the muscle anatomy worked in each exercise, as well as the best variations of these exercises based on current research. It’s also equally important that you are targeting the right back muscles when you perform each of these exercises. I discuss a few “cues” and tips that have helped me minimize the involvement of secondary muscles and focus on using my back throughout each movement."`,
    },{
        nameOfWorkout: "chin-ups",
        muscleGroup: "Biceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "incline dumbell curls",
        muscleGroup: "Biceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "concentration curls",
        muscleGroup: "Biceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "reverse easy bar curls",
        muscleGroup: "Biceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        description: `" In this 2-part video series of the best bicep and tricep workout, I’m going to be discussing the best arm workout and the best arm exercises based on science (10 studies) and our anatomical understanding of the arms. In part 1 of this series, I will be discussing the best bicep exercises and the best bicep workout for size and shape. The bicep curls variations shown in this video will help tremendously in putting more mass on your arms and will help develop your “bicep peak”. But it’s important that you don’t simply think about “getting bigger biceps”, as that should be the goal but equally as important is the shape and definition of your biceps. In order to get well-defined biceps and arms you need to train each part of the biceps – the long head, the short head, and the brachialis (as well as the brachioradialis). All these components, if properly trained, will help build an aesthetic looking arm with size, shape, and definition. "`,
        nameOfWorkout: "close-grip bench press",
        muscleGroup: "Triceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "overhead cable extensions",
        muscleGroup: "Triceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "cable pushdowns",
        muscleGroup: "Triceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        nameOfWorkout: "trangle pushups or bench dips",
        muscleGroup: "Triceps",
        set: "3",
        reps: "6-8",
        comments:[""],
        description:`" In this part 2 video of my arm series, I will discuss the best tricep workout to hit every triceps head based on current scientific literature and our anatomical understanding of the arms. Although it’s important to know that all 3 tricep heads (long head, lateral head, and medial head) will be activated in all movements, we can emphasize the involvement of each of them by choosing the right exercises for each head of the triceps which in a way will provide “tricep head isolation”. These exercises will not only help with increasing tricep size and getting bigger triceps with that “horseshoe triceps” effect, they will also help in improving the overall definition of your triceps and allowing each head to grow in proportion with each other. In my opinion, these are the best exercises for bigger triceps and putting on more tricep mass while keeping them in proportion. "`,
        nameOfWorkout: "standing overhead press",
        muscleGroup: "Shoulders",
        set: "3-4",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "db lateral raises",
        muscleGroup: "Shoulders",
        set: "4",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "reverse pec deck",
        muscleGroup: "Shoulders",
        set: "4",
        reps: "6-10",
        comments:[""],
        nameOfWorkout: "lying face pulls",
        muscleGroup: "Shoulders",
        set: "2",
        reps: "8-12",
        comments:[""],
        nameOfWorkout: "standing or kneeling face pulls",
        muscleGroup: "Shoulders",
        set: "2",
        reps: "8-12",
        comments:[""],
        instruction:`" When it comes to the “best shoulder workout”, you have to consider training all three heads of the shoulder. These include the front delt, mid delt (or “side delt”) and the rear delt. These three heads are what really build huge shoulders and give a “3d shoulders” or “cannonball” look. Although all 3 heads will be activated to an extent during all shoulder exercises, as shown in the literature certain shoulder heads can be emphasized by choosing the right shoulder exercises and manipulating the way you perform them. It’s also important to note that the front delts already get sufficient activation in many pressing movements. Thus, you should focus more on the development of the lateral and posterior (mid and side) delts in order to build bigger delts. In this video I’ll go through the best shoulder exercises and the best shoulder workout for mass based on scientific literature and our anatomical understanding of the shoulder muscles."`,
        nameOfWorkout: "farmers walk",
        muscleGroup: "Forearms",
        set: "1 each arm",
        reps: "30 seconds",
        comments:[""],
        nameOfWorkout: "wrist rollers",
        muscleGroup: "Forearms",
        set: "1 each arm",
        reps: "30 seconds",
        comments:[""],
        nameOfWorkout: "standing wrist curls",
        muscleGroup: "Forearms",
        set: "2-3",
        reps: "15-20",
        comments:[""],
        nameOfWorkout: "standing wrist extensions",
        muscleGroup: "Forearms",
        set: "2-3",
        reps: "15-20",
        comments:[""],
        instructions:`" When it comes to growing big forearms and improving your grip strength, you need to consider the anatomy of the forearms in order to determine what the “best forearm workout” might be. In this video I’ll show you guys the best forearm exercises combined into a forearm workout to help boost your forearm size as well as your forearm strength (grip strength). This can be used as a forearm workout for mass but is also considered a grip strength workout given the inclusion of the suitcase holds and wrist rollers."`
    },{
        nameOfWorkout: "weighted hanging leg raises",
        muscleGroup: "Core",
        set: "4",
        reps: "6-15",
        comments:[""],
        nameOfWorkout: "ab pulldowns",
        muscleGroup: "Core",
        set: "4",
        reps: "6-15",
        comments:[""],
        nameOfWorkout: "cable wood-choppers",
        muscleGroup: "Core",
        set: "4",
        reps: "6-15",
        comments:[""],
        nameOfWorkout: "flutter-kicks",
        muscleGroup: "Core",
        set: "4",
        reps: "until failure",
        comments:[""],
        description: `" If you want a well-defined, impressive looking six pack then you need to incorporate weighted abs exercises into your ab training routine! These exercises allow you to easily progressively overload your abs with weight in order to grow your abs and get them to “pop out” more. In this video I’ll be going through the 4 best weighted ab exercises, and show how you can incorporate them into an weighted ab routine. I often get asked if you should do ab exercises with weights, and in my opinion if you want your abs to “pop” then using a weighted ab routine is a must!"`,
    },{
        nameOfWorkout: "barbell back squats",
        muscleGroup: "Legs",
        set: "3",
        reps: "6-10, 12-15",
        comments:[""],
        nameOfWorkout: "front squats",
        muscleGroup: "Legs",
        set: "3",
        reps: "6-10, 12-15",
        comments:[""],
        nameOfWorkout: "bulgarian split",
        muscleGroup: "Legs",
        set: "3",
        reps: "6-10, 12-15",
        comments:[""],
        nameOfWorkout: "weighted hip thrusts",
        muscleGroup: "Legs",
        set: "3",
        reps: "10-15",
        comments:[""],
        instruction: `" In this video I’m going to be covering the “best” leg workout for mass and strong legs based on scientific literature and our understanding of the leg muscles. I’ll go through the most effective leg exercises that best activate the glutes, quadriceps, and hamstrings. These exercises are great for men and women, if your goal is leg hypertrophy (bigger legs) from your leg workouts. The four exercises I will discuss are the barbell back squat, front squat, Bulgarian split squat, and hip thrusts for glutes using a barbell. This combination of bilateral and unilateral leg exercises is ideal in order to add mass to the leg while correcting asymmetries that would be caused by only using bilateral exercises. Stick around until the end where I provide a full sample leg workout you guys can get started with right away."`,
    }
]

muscleInfo = module.exports